remote_theme: pages-themes/cayman@v0.2.0
theme: jekyll-theme-cayman
plugins:
- jekyll-remote-theme 

title: IACTA-EST 2023
description: The Image Analysis for CTA Endovascular Stroke Therapy (IACTA-EST) Data Challenge
